CREATE DATABASE Store

USE Store
GO

CREATE TABLE Cities
(
CityID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL
);

CREATE TABLE Customers
(
CustomerID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
Birthday DATE NOT NULL,
CityID INT NOT NULL,
CONSTRAINT FK_CustomersCities FOREIGN KEY (CityID)
REFERENCES Cities(CityID)
);

CREATE TABLE Orders
(
OrderID INT PRIMARY KEY IDENTITY(1,1),
CustomerID INT NOT NULL
CONSTRAINT FK_OrdersCustomers FOREIGN KEY (CustomerID)
REFERENCES Customers(CustomerID)
);

CREATE TABLE ItemTypes
(
ItemTypeID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL
);

CREATE TABLE Items
(
ItemID INT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(50) NOT NULL,
ItemTypeID INT NOT NULL,
CONSTRAINT FK_ItemsItemTypes FOREIGN KEY (ItemTypeID)
REFERENCES ItemTypes(ItemTypeID)
);

CREATE TABLE OrderItems
(
OrderID INT NOT NULL,
ItemID INT NOT NULL,
CONSTRAINT PK_OrderItem PRIMARY KEY (OrderID, ItemID),
CONSTRAINT FK_OrdersItemsOrders FOREIGN KEY (OrderID)
REFERENCES Orders(OrderID),
CONSTRAINT FK_ItemsItemsOrders FOREIGN KEY (ItemID)
REFERENCES Items(ItemID),
);